version: 2
jobs:
  build:
    docker:
      - image: vinayraikar/hugo-firebase:latest

    working_directory: ~/repo
    steps:
      - checkout
      - run: ./run clean
      - run: ./run build
      - run: ./run deploy
